INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (99, 123.45, 'Bob');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (100, 1.00, 'Bob');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (101, 150.00, 'Bob');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (102, 25.00, 'Joe');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (103, 5.00, 'Joe');
